server:
  port: 8085
 
spring:
   application:
       name: CONFIG-SERVER
   cloud:
     config:
       server:
         git:
           uri: https://github.com/Saroj547/micro-Config1-
           clone-on-start: true