server:
  port: 0
  
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/microservices2
      username: root
      password: Madhu123@
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
  application:
       name: RATING-SERVICE
       
  config:
     import: optional:configserver:http://localhost8085
#eureka:
#   instance:
#      prefer-ip-address: true
#   client:
#      fetch-registry: true
#      service-url:
#        defaultZone: http://localhost:8761/eureka
      