server:
  port: 0
  
spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/microservices
      username: postgres
      password: Saroj123@
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  application:
       name: HOTEL-SERVICE
       
  config:
     import: optional:configserver:http://localhost8085
#eureka:
#   instance:
#      prefer-ip-address: true
#   client:
#      fetch-registry: true
#      service-url:
#        defaultZone: http://localhost:8761/eureka
#      
